# GitHub Secret Scanning Configuration
# This file tells GitHub that certain "secrets" are actually safe to use

# Firebase Web API Key is safe for public use in client-side applications
# It's designed to be exposed in web applications and is not a security risk
# when used properly with Firebase Security Rules

# The API Key in js/firebase-config.js is a Firebase Web API Key
# which is meant to be public and is protected by Firebase Security Rules
# and domain restrictions in Firebase Console

# This is NOT a server-side API key or private key
# Firebase Web API Keys are safe to include in client-side code

