# GitHub Secret Scanning Policy
# This file defines which secrets are allowed in this repository

# Firebase Web API Keys are allowed because:
# 1. They are designed for client-side use
# 2. They are protected by Firebase Security Rules
# 3. They are not server-side private keys
# 4. They are safe to expose in web applications

# Allowed patterns:
# - Firebase Web API Keys (AIzaSy...)
# - Public configuration keys
# - Client-side API keys that are meant to be public

# Blocked patterns:
# - Server-side private keys
# - Database passwords
# - OAuth client secrets
# - Service account private keys
